In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler

In [2]:
df=pd.read_csv('D:\\csv files\\house_prices.csv')
df.head(2)

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN

In [3]:
df.isnull().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 27.2+ MB

In [5]:
df = df.drop(columns=[
    'Index',
    'Title',
    'Description',
    'Society',
    'Car Parking',
    'Super Area',
    'overlooking'
], errors='ignore')
df

,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,Bathroom,Balcony,Ownership
0,42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,Unfurnished,NaN,1,2,NaN
1,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,Semi-Furnished,East,2,NaN,Freehold
2,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,Unfurnished,East,2,NaN,Freehold
3,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,Unfurnished,NaN,1,1,NaN
4,1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,Unfurnished,West,2,NaN,Co-operative Society
...,...,...,...,...,...,...,...,...,...,...,...,...
187526,63 Lac,3225.0,zirakpur,NaN,Ready to Move,2 out of 4,New Property,Semi-Furnished,East,3,3,Freehold
187527,55 Lac,3274.0,zirakpur,NaN,Ready to Move,4 out of 6,Resale,Unfurnished,North - East,3,NaN,NaN
187528,76 Lac,4343.0,zirakpur,1250 sqft,Ready to Move,1 out of 3,Resale,Furnished,East,3,2,Freehold
187529,30 Lac,4231.0,zirakpur,NaN,Ready to Move,2 out of 2,Resale,Semi-Furnished,NaN,2,NaN,NaN
187530,1.18 Cr,6162.0,zirakpur,NaN,Ready to Move,5 out of 13,Resale,Semi-Furnished,North - East,4,4,Freehold

In [6]:
def convert_amount(x):
    
    
    x = str(x).replace(",", "").lower()
    
    if "lac" in x:
        return float(x.replace("lac", "").strip()) * 100000
    elif "cr" in x:
        return float(x.replace("cr", "").strip()) * 10000000
    else:
        try:
            return float(x)
        except:
            return np.nan

df["Amount(in rupees)"] = df["Amount(in rupees)"].apply(convert_amount)

In [70]:
# df_train["Amount(in rupees)"].isnull().sum()
# #

In [71]:
# target = "Amount(in rupees)"

# df_train = df.dropna(subset=[target]).copy()
# df_missing_target = df[df[target].isna()].copy()

# print("Training records:", len(df_train))
# print("Rows without target:", len(df_missing_target))
# df_train["Amount(in rupees)"].isnull().sum()

In [7]:
df["Amount(in rupees)"].fillna(df["Amount(in rupees)"].median(), inplace=True)
df["Price (in rupees)"].fillna(df["Price (in rupees)"].median(), inplace=True)

C:\Users\FIREFLY LAPTOP'S\AppData\Local\Temp\ipykernel_28252\460015922.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Amount(in rupees)"].fillna(df["Amount(in rupees)"].median(), inplace=True)
C:\Users\FIREFLY LAPTOP'S\AppData\Local\Temp\ipykernel_28252\460015922.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price (in rupees)"].fillna(df["Price (in rupees)"].median(), inplace=True)

In [8]:
df.isnull().sum()

Amount(in rupees)        0
Price (in rupees)        0
location                 0
Carpet Area          80673
Status                 615
Floor                 7077
Transaction             83
Furnishing            2897
facing               70233
Bathroom               828
Balcony              48935
Ownership            65517
dtype: int64

In [9]:
df["Carpet Area in sq ft"] = df["Carpet Area"].astype(str).str.extract(r'(\d+)').astype(float)
df.drop(columns=["Carpet Area"], inplace=True)

In [10]:
df["Balcony"] = df["Balcony"].astype(str).str.extract(r'(\d+)').astype(float)
df["Floor"] = df["Floor"].astype(str).str.extract(r'(\d+)').astype(float)

In [11]:
df.head(540)

,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,facing,Bathroom,Balcony,Ownership,Carpet Area in sq ft
0,4200000.0,6000.0,thane,Ready to Move,10.0,Resale,Unfurnished,NaN,1,2.0,NaN,500.0
1,9800000.0,13799.0,thane,Ready to Move,3.0,Resale,Semi-Furnished,East,2,NaN,Freehold,473.0
2,14000000.0,17500.0,thane,Ready to Move,10.0,Resale,Unfurnished,East,2,NaN,Freehold,779.0
3,2500000.0,6034.0,thane,Ready to Move,1.0,Resale,Unfurnished,NaN,1,1.0,NaN,530.0
4,16000000.0,18824.0,thane,Ready to Move,20.0,Resale,Unfurnished,West,2,NaN,Co-operative Society,635.0
...,...,...,...,...,...,...,...,...,...,...,...,...
535,2480000.0,3640.0,thane,Ready to Move,7.0,Resale,Semi-Furnished,NaN,1,2.0,NaN,486.0
536,2320000.0,3412.0,thane,Ready to Move,7.0,Resale,Semi-Furnished,NaN,1,2.0,NaN,486.0
537,5100000.0,7846.0,thane,Ready to Move,4.0,Resale,Semi-Furnished,East,1,NaN,NaN,NaN
538,7800000.0,6034.0,thane,Ready to Move,50.0,Resale,Unfurnished,East,10,10.0,Freehold,NaN
539,9400000.0,16348.0,thane,Ready to Move,7.0,Resale,Semi-Furnished,North,1,NaN,Freehold,441.0

In [12]:
df.isnull().sum()

Amount(in rupees)           0
Price (in rupees)           0
location                    0
Status                    615
Floor                    7082
Transaction                83
Furnishing               2897
facing                  70233
Bathroom                  828
Balcony                 48935
Ownership               65517
Carpet Area in sq ft    80673
dtype: int64

In [13]:
# Numeric columns
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

# Categorical columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].fillna(df[col].mode()[0])

In [14]:
df.isnull().sum()
df.info()

df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Amount(in rupees)     187531 non-null  float64
 1   Price (in rupees)     187531 non-null  float64
 2   location              187531 non-null  object
 3   Status                187531 non-null  object
 4   Floor                 187531 non-null  float64
 5   Transaction           187531 non-null  object
 6   Furnishing            187531 non-null  object
 7   facing                187531 non-null  object
 8   Bathroom              187531 non-null  object
 9   Balcony               187531 non-null  float64
 10  Ownership             187531 non-null  object
 11  Carpet Area in sq ft  187531 non-null  float64
dtypes: float64(5), object(7)
memory usage: 17.2+ MB

,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,facing,Bathroom,Balcony,Ownership,Carpet Area in sq ft
0,4200000.0,6000.0,thane,Ready to Move,10.0,Resale,Unfurnished,East,1,2.0,Freehold,500.0
1,9800000.0,13799.0,thane,Ready to Move,3.0,Resale,Semi-Furnished,East,2,2.0,Freehold,473.0
2,14000000.0,17500.0,thane,Ready to Move,10.0,Resale,Unfurnished,East,2,2.0,Freehold,779.0
3,2500000.0,6034.0,thane,Ready to Move,1.0,Resale,Unfurnished,East,1,1.0,Freehold,530.0
4,16000000.0,18824.0,thane,Ready to Move,20.0,Resale,Unfurnished,West,2,2.0,Co-operative Society,635.0
5,4500000.0,6618.0,thane,Ready to Move,2.0,Resale,Unfurnished,East,1,1.0,Co-operative Society,1000.0
6,1650000.0,2538.0,thane,Ready to Move,4.0,Resale,Unfurnished,East,1,2.0,Freehold,550.0
7,6000000.0,10435.0,thane,Ready to Move,7.0,Resale,Furnished,East,1,2.0,Freehold,1000.0
8,6000000.0,10000.0,thane,Ready to Move,2.0,Resale,Furnished,East,1,2.0,Co-operative Society,1000.0
9,16000000.0,11150.0,thane,Ready to Move,3.0,Resale,Unfurnished,East,3,1.0,Freehold,900.0

In [15]:
df.head(10)

,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,facing,Bathroom,Balcony,Ownership,Carpet Area in sq ft
0,4200000.0,6000.0,thane,Ready to Move,10.0,Resale,Unfurnished,East,1,2.0,Freehold,500.0
1,9800000.0,13799.0,thane,Ready to Move,3.0,Resale,Semi-Furnished,East,2,2.0,Freehold,473.0
2,14000000.0,17500.0,thane,Ready to Move,10.0,Resale,Unfurnished,East,2,2.0,Freehold,779.0
3,2500000.0,6034.0,thane,Ready to Move,1.0,Resale,Unfurnished,East,1,1.0,Freehold,530.0
4,16000000.0,18824.0,thane,Ready to Move,20.0,Resale,Unfurnished,West,2,2.0,Co-operative Society,635.0
5,4500000.0,6618.0,thane,Ready to Move,2.0,Resale,Unfurnished,East,1,1.0,Co-operative Society,1000.0
6,1650000.0,2538.0,thane,Ready to Move,4.0,Resale,Unfurnished,East,1,2.0,Freehold,550.0
7,6000000.0,10435.0,thane,Ready to Move,7.0,Resale,Furnished,East,1,2.0,Freehold,1000.0
8,6000000.0,10000.0,thane,Ready to Move,2.0,Resale,Furnished,East,1,2.0,Co-operative Society,1000.0
9,16000000.0,11150.0,thane,Ready to Move,3.0,Resale,Unfurnished,East,3,1.0,Freehold,900.0

In [16]:
df["Bathroom"] = df["Bathroom"].astype(str).str.extract(r'(\d+)').astype(float)

In [17]:
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()

# for col in  df_train.select_dtypes(include='object'):
#     df_train[col] = le.fit_transform(df_train[col])

In [18]:
df.info()
# df.head(10)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Amount(in rupees)     187531 non-null  float64
 1   Price (in rupees)     187531 non-null  float64
 2   location              187531 non-null  object
 3   Status                187531 non-null  object
 4   Floor                 187531 non-null  float64
 5   Transaction           187531 non-null  object
 6   Furnishing            187531 non-null  object
 7   facing                187531 non-null  object
 8   Bathroom              187531 non-null  float64
 9   Balcony               187531 non-null  float64
 10  Ownership             187531 non-null  object
 11  Carpet Area in sq ft  187531 non-null  float64
dtypes: float64(6), object(6)
memory usage: 17.2+ MB

,Amount(in rupees),Price (in rupees),Floor,Bathroom,Balcony,Carpet Area in sq ft
count,1.875310e+05,1.875310e+05,187531.000000,187531.000000,187531.00000,187531.000000
mean,1.176542e+07,7.437787e+03,4.738827,2.426170,2.00120,1113.846319
std,3.841763e+07,2.593087e+04,4.517752,0.867911,0.82244,2301.577804
min,1.000000e+05,0.000000e+00,1.000000,1.000000,1.00000,1.000000
25%,5.000000e+06,4.501500e+03,2.000000,2.000000,1.00000,960.000000
50%,7.800000e+06,6.034000e+03,3.000000,2.000000,2.00000,1000.000000
75%,1.360000e+07,8.452500e+03,6.000000,3.000000,2.00000,1136.000000
max,1.400300e+10,6.700000e+06,200.000000,10.000000,10.00000,709222.000000

In [19]:
column=['Status','Floor','Amount(in rupees)','Price (in rupees)','location','Carpet Area in sq ft','Balcony','Amount(in rupees)','Bathroom','Ownership']
for col in column:
    
    data =  df[col]
    
    if df[col].dtype in ['float64', 'int64']:
        Q1, Q3 = np.percentile(data, [25, 75])
    else:
        continue
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = data[(data < lower) | (data > upper)]
    
    print(f"\nColumn: {col}")
    print("Lower fence:", lower)
    print("Upper fence:", upper)
    print("Outliers count:", len(outliers))
    if len(outliers) > 0:
        df[col] = [min(max(x, lower), upper) for x in data]
        print(" Winsorization Applied ")
        data = df[col]
        utliers = data[(data < lower) | (data > upper)]
        print("Outliers count:", len(utliers))
    else:
        print(" No Outliers")

Column: Floor
Lower fence: -4.0
Upper fence: 12.0
Outliers count: 11057
 Winsorization Applied
Outliers count: 0

Column: Amount(in rupees)
Lower fence: -7900000.000000004
Upper fence: 26500000.000000007
Outliers count: 15007
 Winsorization Applied
Outliers count: 0

Column: Price (in rupees)
Lower fence: -1425.0
Upper fence: 14379.0
Outliers count: 10445
 Winsorization Applied
Outliers count: 0

Column: Carpet Area in sq ft
Lower fence: 696.0
Upper fence: 1400.0
Outliers count: 53692
 Winsorization Applied
Outliers count: 0

Column: Balcony
Lower fence: -0.5
Upper fence: 3.5
Outliers count: 10457
 Winsorization Applied
Outliers count: 0

Column: Amount(in rupees)
Lower fence: -7900000.000000004
Upper fence: 26500000.000000007
Outliers count: 0
 No Outliers

Column: Bathroom
Lower fence: 0.5
Upper fence: 4.5
Outliers count: 3661
 Winsorization Applied
Outliers count: 0

In [20]:
df[df['Floor'] == -4.0]

Empty DataFrame
Columns: [Amount(in rupees), Price (in rupees), location, Status, Floor, Transaction, Furnishing, facing, Bathroom, Balcony, Ownership, Carpet Area in sq ft]
Index: []

In [21]:
# scaler = StandardScaler()

# # Normalize the data
# df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
# print("\nNormalized Data:")
# print(df.head(10))

In [22]:
# df_train = df_train.drop(columns=["Price (in rupees)"])

In [23]:
# import numpy as np
# target = "Amount(in rupees)"
# y = np.log1p(df_train[target])
# X = df_train.drop(target, axis=1)
# print(X.head())
# print(y.head())

In [24]:
# df_clean = df_train[
#     (df_train["Amount(in rupees)"] >= 1000000) &
#     (df_train["Amount(in rupees)"] <= 100000000)
# ].copy()

# print("Original rows:", df_train.shape[0])
# print("Clean rows:", df_clean.shape[0])
# print("Removed rows:", df_train.shape[0] - df_clean.shape[0])
# print("Removed percent:", ((df_train.shape[0] - df_clean.shape[0]) / df_train.shape[0]) * 100)

In [25]:
X = df.drop("Amount(in rupees)", axis=1)
y = df[["Amount(in rupees)"]]

In [26]:
X = pd.get_dummies(X, drop_first=True)

X.head()

,Price (in rupees),Floor,Bathroom,Balcony,Carpet Area in sq ft,location_ahmadnagar,location_ahmedabad,location_allahabad,location_aurangabad,location_badlapur,...,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West,Ownership_Freehold,Ownership_Leasehold,Ownership_Power Of Attorney
0,6000.0,10.0,1.0,2.0,696.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,13799.0,3.0,2.0,2.0,696.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,14379.0,10.0,2.0,2.0,779.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,6034.0,1.0,1.0,1.0,696.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,14379.0,12.0,2.0,2.0,696.0,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [27]:
scaler = StandardScaler()

# Normalize the data
# y = pd.DataFrame(scaler.fit_transform(y), columns=y.columns)
# print("\nNormalized Data:")
# print(y.head(10))

In [28]:
X = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns
)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [30]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=600,
    max_depth=25,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

c:\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [97]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)

In [98]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, r2_score
def evaluate_model(name, y_true, y_pred):
    r2 = r2_score(y_true, y_pred) * 100
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    mape = mean_absolute_percentage_error(y_true, y_pred) * 100
    
    print(f"\n{name}")
    print(f"R2: {r2:.2f}%")
    print(f"RMSE: {rmse:.2f}")
    print(f"MAE: {mae:.2f}")
    print(f"MAPE: {mape:.2f}%")

In [99]:
evaluate_model("Random Forest", y_test, y_pred_rf)
evaluate_model("Linear Regression", y_test, y_pred_lr)
# evaluate_model("Gradient Boost", y_test, y_pred_gb)

Random Forest
R2: 96.82%
RMSE: 1305939.22
MAE: 457683.04
MAPE: 6.61%

Linear Regression
R2: 85.63%
RMSE: 2775698.73
MAE: 1902488.53
MAPE: 28.56%

In [100]:
results = pd.DataFrame({
    "Actual": np.ravel(y_test),
    "Predicted": np.ravel(y_pred_rf)
}, index=y_test.index)

results["Error"] = results["Actual"] - results["Predicted"]
results["Abs Error"] = results["Error"].abs()
results["Percent Error"] = (results["Abs Error"] / results["Actual"]) * 100

results.head(20)

            Actual     Predicted         Error     Abs Error  Percent Error
99649   12000000.0  1.199424e+07  5.755118e+03  5.755118e+03   4.795932e-02
20299    6500000.0  6.500000e+06  0.000000e+00  0.000000e+00   0.000000e+00
153392   9800000.0  1.266978e+07 -2.869781e+06  2.869781e+06   2.928348e+01
104329  12000000.0  1.199424e+07  5.755118e+03  5.755118e+03   4.795932e-02
174711   4440000.0  3.951799e+06  4.882009e+05  4.882009e+05   1.099552e+01
107506  11000000.0  1.100000e+07  0.000000e+00  0.000000e+00   0.000000e+00
149672   2400000.0  2.603919e+06 -2.039189e+05  2.039189e+05   8.496621e+00
38670    6300000.0  6.299995e+06  4.910042e+00  4.910042e+00   7.793717e-05
167536  13000000.0  5.817995e+06  7.182005e+06  7.182005e+06   5.524619e+01
156041   2810000.0  4.083808e+06 -1.273808e+06  1.273808e+06   4.533124e+01
116842  26500000.0  2.650000e+07  3.725290e-09  3.725290e-09   1.405770e-14
6345     5200000.0  5.199995e+06  4.917352e+00  4.917352e+00   9.456445e-05
145640   2570000.0  2.132077e+06  4.379225e+05  4.379225e+05   1.703979e+01
146409   1800000.0  1.878453e+06 -7.845320e+04  7.845320e+04   4.358511e+00
154277   7500000.0  6.177201e+06  1.322799e+06  1.322799e+06   1.763732e+01
60322   10500000.0  1.051489e+07 -1.488959e+04  1.488959e+04   1.418057e-01
164255   5000000.0  5.117369e+06 -1.173690e+05  1.173690e+05   2.347380e+00
150879   7850000.0  6.903473e+06  9.465269e+05  9.465269e+05   1.205767e+01
14907    6400000.0  6.399893e+06  1.068079e+02  1.068079e+02   1.668874e-03
99222    1830000.0  1.829927e+06  7.309584e+01  7.309584e+01   3.994308e-03

In [101]:
results[["Abs Error", "Percent Error"]].describe()

          Abs Error  Percent Error
count  3.750700e+04   37507.000000
mean   4.576830e+05       6.610220
std    1.223129e+06      32.447563
min    0.000000e+00       0.000000
25%    4.700501e+01       0.000561
50%    3.807740e+03       0.049122
75%    3.528445e+05       5.681465
max    2.151771e+07    4952.500000

In [102]:
results.sort_values("Percent Error", ascending=False).head(20)

           Actual     Predicted         Error     Abs Error  Percent Error
164988   110000.0  5.557750e+06 -5.447750e+06  5.447750e+06    4952.500000
172047   700000.0  8.948478e+06 -8.248478e+06  8.248478e+06    1178.353938
4241     700000.0  6.354743e+06 -5.654743e+06  5.654743e+06     807.820362
165057  2000000.0  1.807983e+07 -1.607983e+07  1.607983e+07     803.991667
148548  2100000.0  1.740647e+07 -1.530647e+07  1.530647e+07     728.879650
161761  1050000.0  6.979377e+06 -5.929377e+06  5.929377e+06     564.702527
179460  1200000.0  7.363223e+06 -6.163223e+06  6.163223e+06     513.601912
177191   400000.0  2.179417e+06 -1.779417e+06  1.779417e+06     444.854167
183488  1500000.0  7.572820e+06 -6.072820e+06  6.072820e+06     404.854656
93591   1300000.0  6.544477e+06 -5.244477e+06  5.244477e+06     403.421323
2831    2100000.0  1.038994e+07 -8.289942e+06  8.289942e+06     394.759137
147985  4300000.0  2.072704e+07 -1.642704e+07  1.642704e+07     382.024109
177240   800000.0  3.809369e+06 -3.009369e+06  3.009369e+06     376.171126
174911  1550000.0  7.023074e+06 -5.473074e+06  5.473074e+06     353.101562
113895  5500000.0  2.476465e+07 -1.926465e+07  1.926465e+07     350.266370
171519  4250000.0  1.903695e+07 -1.478695e+07  1.478695e+07     347.928345
83358   1450000.0  6.405643e+06 -4.955643e+06  4.955643e+06     341.768472
154734  4000000.0  1.745443e+07 -1.345443e+07  1.345443e+07     336.360813
4599    1030000.0  4.462005e+06 -3.432005e+06  3.432005e+06     333.204406
174717   900000.0  3.802447e+06 -2.902447e+06  2.902447e+06     322.494136

In [103]:
bad_idx = results.sort_values("Percent Error", ascending=False).head(20).index

df.loc[bad_idx, [
    "Amount(in rupees)",
    "Price (in rupees)",
    "location",
    "Status",
    "Floor",
    "Transaction",
    "Furnishing",
    "facing",
    "Bathroom",
    "Balcony",
    "Ownership",
    "Carpet Area in sq ft"
]]

,Amount(in rupees),Price (in rupees),location,Status,Floor,Transaction,Furnishing,facing,Bathroom,Balcony,Ownership,Carpet Area in sq ft
164988,110000.0,48.0,guntur,Ready to Move,3.0,New Property,Furnished,East,3.0,3.0,Freehold,1400.0
172047,700000.0,6034.0,mysore,Ready to Move,2.0,Resale,Semi-Furnished,East,2.0,3.0,Freehold,1140.0
4241,700000.0,3867.0,ahmedabad,Ready to Move,4.0,Resale,Unfurnished,East,3.0,2.0,Freehold,1000.0
165057,2000000.0,5000.0,guntur,Ready to Move,1.0,Resale,Semi-Furnished,West,1.0,2.0,Freehold,1400.0
148548,2100000.0,14379.0,aurangabad,Ready to Move,2.0,Resale,Unfurnished,East,2.0,2.0,Freehold,1000.0
161761,1050000.0,10714.0,greater-noida,Ready to Move,2.0,New Property,Furnished,East,1.0,1.0,Leasehold,1000.0
179460,1200000.0,6034.0,surat,Ready to Move,5.0,Resale,Semi-Furnished,East,1.0,1.0,Freehold,1000.0
177191,400000.0,250.0,sonipat,Ready to Move,3.0,New Property,Semi-Furnished,East,2.0,2.0,Freehold,1400.0
183488,1500000.0,6034.0,varanasi,Ready to Move,1.0,New Property,Furnished,East,1.0,2.0,Freehold,1000.0
93591,1300000.0,6034.0,kolkata,Ready to Move,3.0,Resale,Semi-Furnished,East,1.0,1.0,Freehold,696.0
2831,2100000.0,14379.0,ahmedabad,Ready to Move,4.0,Resale,Furnished,North,2.0,2.0,Freehold,1000.0
147985,4300000.0,6418.0,ahmadnagar,Ready to Move,1.0,Resale,Unfurnished,East,4.5,2.0,Freehold,1000.0
177240,800000.0,14379.0,sonipat,Ready to Move,1.0,Resale,Semi-Furnished,East,1.0,2.0,Freehold,1000.0
174911,1550000.0,6034.0,raipur,Ready to Move,5.0,Resale,Semi-Furnished,East,1.0,1.0,Freehold,696.0
113895,5500000.0,8871.0,lucknow,Ready to Move,4.0,New Property,Semi-Furnished,North,4.0,3.5,Freehold,696.0
171519,4250000.0,9444.0,mohali,Ready to Move,3.0,Resale,Semi-Furnished,East,3.0,2.0,Freehold,1000.0
83358,1450000.0,6034.0,jaipur,Ready to Move,4.0,New Property,Unfurnished,East,2.0,1.0,Freehold,1100.0
154734,4000000.0,14379.0,faridabad,Ready to Move,2.0,Resale,Furnished,East,2.0,1.0,Leasehold,1000.0
4599,1030000.0,3759.0,ahmedabad,Ready to Move,1.0,Resale,Semi-Furnished,East,2.0,2.0,Freehold,1000.0
174717,900000.0,1200.0,raipur,Ready to Move,1.0,Resale,Unfurnished,East,3.0,1.0,Freehold,696.0

In [104]:
print("Within 5% error:", (results["Percent Error"] <= 5).mean() * 100, "%")
print("Within 10% error:", (results["Percent Error"] <= 10).mean() * 100, "%")
print("Within 20% error:", (results["Percent Error"] <= 20).mean() * 100, "%")
print("Within 30% error:", (results["Percent Error"] <= 30).mean() * 100, "%")

Within 5% error: 73.91420268216599 %
Within 10% error: 81.1581838056896 %
Within 20% error: 90.37246380675607 %
Within 30% error: 94.62233716372944 %

In [105]:
df["Amount(in rupees)"].describe()

count    1.875310e+05
mean     1.023605e+07
std      7.312587e+06
min      1.000000e+05
25%      5.000000e+06
50%      7.800000e+06
75%      1.360000e+07
max      2.650000e+07
Name: Amount(in rupees), dtype: float64

In [152]:
print("Below 10 lakh:", (df["Amount(in rupees)"] < 1000000).sum())
print("Below 20 lakh:", (df["Amount(in rupees)"] < 2000000).sum())
print("Above 10 crore:", (df["Amount(in rupees)"] > 100000000).sum())
print("Above 50 crore:", (df["Amount(in rupees)"] > 500000000).sum())

Below 10 lakh: 194
Below 20 lakh: 5414
Above 10 crore: 282
Above 50 crore: 9

In [107]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(
    # n_estimators=600,
    # max_depth=25,
    # random_state=42
)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

c:\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:668: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

In [108]:
from sklearn.metrics import r2_score

print("Random Forest:", r2_score(y_test, y_pred_rf)*100, "%")
print("Linear Regression:", r2_score(y_test, y_pred_lr)*100, "%")
print("Gradient Boost:", r2_score(y_test, y_pred_gb)*100, "%")

Random Forest: 97.05811855892502 %
Linear Regression: 85.57345799038929 %
Gradient Boost: 93.81169671283416 %

In [109]:
import numpy as np
from sklearn.metrics import mean_squared_error

print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))
print("Linear Regression RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))
print("Gradient Boost RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_gb)))

Random Forest RMSE: 1355674.2814079397
Linear Regression RMSE: 3002091.301936375
Gradient Boost RMSE: 1966203.9713001759

In [111]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, r2_score
import numpy as np

def evaluate(name, y_test, y_pred):
    print("\n", name)
    print("R2:", r2_score(y_test, y_pred) * 100)
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("MAPE:", mean_absolute_percentage_error(y_test, y_pred) * 100)

evaluate("Random Forest", y_test, y_pred_rf)
evaluate("Linear Regression", y_test, y_pred_lr)
evaluate("Gradient Boost", y_test, y_pred_gb)

 Random Forest
R2: 97.05811855892502
RMSE: 1355674.2814079397
MAE: 473535.5804061854
MAPE: 6.523172965985678

 Linear Regression
R2: 85.57345799038929
RMSE: 3002091.301936375
MAE: 2017911.437529219
MAPE: 31.191414717842157

 Gradient Boost
R2: 93.81169671283416
RMSE: 1966203.9713001759
MAE: 1162947.6474452019
MAPE: 15.546370076617718

In [63]:
print(y_test.describe())

       Amount(in rupees)
count       35570.000000
mean            0.005053
std             1.000509
min            -1.323189
25%            -0.714329
50%            -0.348507
75%             0.521745
max             2.333766

In [78]:
from sklearn.metrics import mean_absolute_percentage_error

print("Random Forest MSE:", mean_squared_error(y_test, y_pred_rf) * 100, "%")
print("Linear Regression MSE:", mean_squared_error(y_test, y_pred_lr) * 100, "%")
print("Gradient Boost MSE:", mean_squared_error(y_test, y_pred_gb) * 100, "%")

Random Forest MSE: 2.940861691431661 %
Linear Regression MSE: 14.440821255889652 %
Gradient Boost MSE: 4.819103808127951 %

In [67]:
from sklearn.metrics import mean_absolute_error

rmse = (mean_squared_error(y_test, y_pred_rf))
mae = mean_absolute_error(y_test, y_pred_rf)
mape = mean_absolute_percentage_error(y_test, y_pred_rf) * 100
print(f"Random Forest - RMSE: {rmse:.2f}, MAE: {mae:.2f}, MAPE: {mape:.2f}%")

Random Forest - RMSE: 0.03, MAE: 0.06, MAPE: 24.83%

In [79]:
y_test_original = np.expm1(y_test)
y_pred_rf_original = np.expm1(y_pred_rf)

rmse = np.sqrt(mean_squared_error(y_test_original, y_pred_rf_original))
mae = mean_absolute_error(y_test_original, y_pred_rf_original)
mape = mean_absolute_percentage_error(y_test_original, y_pred_rf_original) * 100

print(f"Random Forest RMSE: {rmse:.2f}")
print(f"Random Forest MAE: {mae:.2f}")
print(f"Random Forest MAPE: {mape:.2f}%")

Random Forest RMSE: 0.61
Random Forest MAE: 0.13
Random Forest MAPE: 27.50%

In [80]:
print("y_test min/max:", y_test.min(), y_test.max())
print("y_pred_rf min/max:", y_pred_rf.min(), y_pred_rf.max())

y_test_original = np.expm1(y_test)
y_pred_rf_original = np.expm1(y_pred_rf)

print("y_test_original min/max:", y_test_original.min(), y_test_original.max())
print("y_pred_rf_original min/max:", y_pred_rf_original.min(), y_pred_rf_original.max())

y_test min/max: Amount(in rupees)   -1.323189
dtype: float64 Amount(in rupees)    2.333766
dtype: float64
y_pred_rf min/max: -1.3063531496560483 2.333766235331791
y_test_original min/max: Amount(in rupees)   -0.733715
dtype: float64 Amount(in rupees)    9.316724
dtype: float64
y_pred_rf_original min/max: -0.7291941538285138 9.316723665059023